version: '3.9'
services:
  postgres:
    image: postgres:16
    container_name: banking-postgres
    environment:
      POSTGRES_DB: banking_system
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
